create table if not exists INCIDENT_RESOLUTION_RULE (
    ID bigint generated by default as identity primary key,
    WORKFLOW_PROCESS_DEFINITION_ID varchar(255) not null,
    PRIORITY integer not null,
    ENABLED boolean not null,
    INSTRUCTION varchar(4000) not null,
    ERROR_TYPES varchar(1000),
    HTTP_STATUS_CODES varchar(1000),
    MESSAGE_CONTAINS varchar(2000),
    RESOLUTION_MODE varchar(64) not null,
    REASON varchar(4000) not null,
    USER_FACING_GUIDANCE varchar(4000),
    CREATED_AT timestamp not null,
    UPDATED_AT timestamp not null
);
