CREATE TABLE incident_resolution_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_process_definition_id VARCHAR(255) NOT NULL,
    priority INTEGER NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    instruction VARCHAR(1000) NOT NULL,
    error_types VARCHAR(500),
    http_status_codes VARCHAR(200),
    message_contains VARCHAR(1000),
    resolution_mode VARCHAR(50) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    user_facing_guidance VARCHAR(2000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_incident_resolution_rule_workflow_enabled_priority
    ON incident_resolution_rule (workflow_process_definition_id, enabled, priority);
